### ISSUE TITLE
There are a bunch of named thralls that literally do nothing.

### ISSUE THREAD

**Issue by mlloy** [Tirocupidus/TheExiledRPOverhaul#115]
Found Rayne of the Rosewood, no special recipes, nothing.

Can those be added in for rare named thralls?

**Comment by gjpeebles** [comment]
Rayne o' the Rosewood *should* have Shaped Wood recipe due to TERPO. The real problem is Funcom hasn't given Rayne his own profession, so he's just a generic "Carpenter_4". I expect Funcom will add some eventually, maybe sooner if this is reported to them. Maybe they haven't done it yet because there aren't any super great carpentry recipes.

Also, none of them should "literally do nothing", as they have crafting speed and material modifiers.

**Comment by gjpeebles** [comment]
Testlive patch notes say T3+ carpenters are getting recipes. Closing this.
