### ISSUE TITLE
T3, T4 or even unique thralls allow crafting certain items independent of user profession

### ISSUE THREAD

**Issue by Midnighit** [Tirocupidus/TheExiledRPOverhaul#30]
To help alleviate profession interdependency to a degree it would be nice if thralls were able to craft certain, often used ingredients like reinforcements and shaped wood. The thralls could be T3, T4 or even just unique spawn depending on how difficult acquisition should be.

**Comment by gjpeebles** [comment]
This is an interesting one. I actually suggested the same thing when Norse was talking about reverting the interdependency due to server population. He thought it would just turn the interdependence concept into a thrall hunt. However, I really like the idea of a *unique* thrall being able to do it—and by "unique", I don't mean a named thrall, but one that is actually unique, meaning it would have to be spawned in, and if I had my way it would be done via a DM event. Having only one, or a small limited number on the server, has the potential for inciting conflict if people want to take the thrall for themselves, which is another point in its favor in my opinion.

**Comment by gjpeebles** [comment]
This should be in the mod, but I forgot to close it.
