### ISSUE TITLE
Brimstone Nodes Broken

### ISSUE THREAD

**Issue by mlloy** [Tirocupidus/TheExiledRPOverhaul#97]
Only getting brimstone once every 3rd swing on average with a steel pick.

**Comment by Midnighit** [comment]
Tested it without mods in a single player game and the problem persists. So it seems like it's not caused by TERPO. I think the problem is that brimstone is in the _secondary loot_ so to speak. Like bark or branches when chopping trees. A byproduct that has the chance to come up at each swing. The amount of brimstone harvested with steel tools when it is harvested at all (4-5) supports this theory.

**Comment by gjpeebles** [comment]
Brimstone has a %5 chance to give salt, and two 25% chances to give you brimstone. Leaving it at vanilla unless it's having a negative effect.
